import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { AiOutlineClose, AiOutlineEdit } from "react-icons/ai";
import { BsInfoCircle } from "react-icons/bs";

const BookModal = ({ book, onClose }) => {
  const [page, setPage] = useState(0);
  const pages = useMemo(() => { const story = String(book.story || "").split(/\n\s*---PAGE---\s*\n/).map((item) => item.trim()).filter(Boolean); return story.length ? story : [book.description || "No preview has been added for this book yet."]; }, [book.description, book.story]);
  useEffect(() => { const close = (event) => event.key === "Escape" && onClose(); document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [onClose]);
  return <div role="dialog" aria-modal="true" aria-label={`Preview of ${book.title}`} onClick={onClose} className="fixed inset-0 z-50 flex items-center justify-center bg-[#15221a]/55 p-4"><div onClick={(event) => event.stopPropagation()} className="animate-pop w-full max-w-xl overflow-hidden rounded-lg border-2 border-[#91a98f] bg-[#fbfff9] shadow-2xl"><div className="flex items-start justify-between border-b border-[#b8cbb5] p-6"><div><p className="eyebrow !text-black">Book preview</p><h2 className="mt-1 font-serif text-2xl font-bold text-black">{book.title}</h2><p className="mt-1 text-sm font-medium text-black">{book.author} · {book.publishYear}</p></div><button type="button" onClick={onClose} className="grid h-8 w-8 place-items-center rounded border border-[#91a98f] text-black hover:bg-[#dcefd8]" aria-label="Close preview"><AiOutlineClose /></button></div><div className="p-6"><p className="whitespace-pre-line text-sm leading-7 text-black">{pages[page]}</p>{pages.length > 1 && <div className="mt-6 flex items-center justify-between border-t border-[#b8cbb5] pt-4"><button type="button" disabled={!page} onClick={() => setPage((current) => current - 1)} className="btn-ghost text-xs disabled:opacity-40">Previous</button><span className="text-xs font-semibold text-black">Page {page + 1} of {pages.length}</span><button type="button" disabled={page === pages.length - 1} onClick={() => setPage((current) => current + 1)} className="btn-ghost text-xs disabled:opacity-40">Next</button></div>}<div className="mt-6 flex gap-2"><Link to={`/books/details/${book._id}`} className="btn-primary text-sm"><BsInfoCircle /> Details</Link><Link to={`/books/edit/${book._id}`} className="btn-ghost text-sm"><AiOutlineEdit /> Edit</Link></div></div></div></div>;
};
export default BookModal;
